BeyondMafia/BeyondMafia-Integration

react_main/src/css/game.css, react_main/src/pages/Game/Game.jsx
Taking care of suggestion #18.
User wants the game name logo to be clickable, and the link will open the lobby page. I took the meaning that they want it open in a new tab, rather than overriding the current page.
=> Add clickable link to lobby that opens in new tab

Games/core/Player.js, data/constants.js
A trick to make the last will extra long by adding new line characters has been seen. This will fix that from happening.
I'm open to trying to find a better way to allow new line characters, but in certain cases where the user actually typed words, and would like to use new lines to separate sentences. Using regex maybe. For now, removing new lines will fix the "exploit" nuisance.
=> Removing new lines from last will

Games/types/Mafia/roles/cards/AssoGunGiver.js
Forgot to include the extra conditions for the valid targets in the associate meeting. Target should be alive, and cannot be mafia.
=> Bugfix for associate role

Games/core/Game.js
pros: it's a quality of life addition for developers, need not have to keep seeing the modal.
cons: unable to use bot accounts to efficiently test the "firstGame" function [need to actually create a new account/ manually disable it in the code]
it's up to you if you want to keep it~=
=> suggestion: do not show "first game" modal for bots

routes/user.js
Re-implemented the YIQ equation isLight() at `/routes/user.js` from [here](https://github.com/Qix-/color/blob/master/index.js#L298). 
The YIQ is a grayscale score from 0 to 1. A smaller number is a darker colour. With a light background, we want users to pick darker colours.
The existing algorithm rejects colours with a score >= 0.5.
I changed it to only reject colours with a score >=0.6.
Personal thoughts: This is quite highly requested but I increasing the value too much might make the site less visually accessible.
=> profile colours: allow users to pick lighter in-game colours

Games/types/Mafia/const/MeetingFlag.js, Games/types/Mafia/roles/cards/SwapRoles.js
I see this "hidden" and "absolute" flag in SwapRoles meeting
if i'm not wrong "hidden" and "absolute" should be labels instead of flags 
don't see a meeting property .hidden or .absolute...
this change was made in a previous commit, i think it was an accident
=> fix: remove meeting flag hidden and absolute

Games/types/Mafia/roles/cards/MeetYourMatch.js, data/roles.js
I originally tested matchmaker with two meetings, then refactored to multimeeting by request, however I realized soon after that multimeeting dramatically nerfs matchmaker because it cannot select the same person twice, making it impossible to win in some situations, so I've reverted that change.
I also allowed matchmaker to count winCount if it exists instead of alignment, allowing non-hostile 3rds to match with town. (And mastermind to match with mafia).
=> [TESTED] slight matchmaker rework

Games/types/Mafia/effects/Famished.js
Eating an orange will now help a player survive a famine. Oranges are edible so they should be able to be eaten in a famine situation.
=> orange now counts as food for famine

Games/types/Mafia/roles/cards/HuntPrey.js, Games/types/Mafia/roles/cards/WinIfTargetDead.js
1. Eat will now not grant immortality unless the target was actually killed, this is a requested departure from how the role worked on EM.
2. VS will not win if they kill themself.
=> Minor role fixes

Games/core/Meeting.js
Fixes #126 
- If the player is going to be the village elimination, do nothing
- Else, veg the player
Most of the code is taken from #324 
The key difference is that in this branch, the village-eliminated player does not get vegPlayer called, it's treated as a normal death - no vegPlayer, no deathType veg, no playerLeave
=> feat: add kickvoting

Games/types/Mafia/roles/cards/WinIfLynched.js, test/Games/Mafia.test.js
I realised that winChecks with `againOnFinished` need to check if winners.group["winGroup"] exists
Fixes #229
=> bugfix: fix jester test case

react_main/src/pages/Game/Game.jsx
Fixes #293 
filter by name always returns no messages
=> bugfix: allow filtering during anon meetings

data/roles.js
Added graveyard participation tags to roles:
graveyardParticipationSelf: players with this role must stay in a ranked game while dead
graveyardParticipationOther: players in a game with this role must stay in a ranked game while dead
=> Added Graveyard Participation

react_main/src/pages/User/Profile.jsx
Fixed the bug where if a profile doesn't have a video, it doesn't load the last loaded video from another profile. Just needed to set the embedId default when loading new profile.
=> Video dupe fix

Games/types/Mafia/Action.js, Games/types/Mafia/roles/cards/MakeVisitorsInsane.js, Games/types/Mafia/roles/cards/WatchPlayer.js
Fixes #539 
thulu 
watcher
**roles - egg = cop, nabila = thulu, markson = watcher, aimee = justice**
=> bugfix(thulu, watcher): use getVisitors to properly check for hidden visitors and multimeeting visitors

react_main/src/css/alerts.css, react_main/src/css/main.css
For real now: I edited the css of the alert and the overall page so that the alerts aren't in the way and in an awkward manner.
Alerts now have a max size comparable to the text they have inside, and the banner (and everything below) is a couple pixels lower so that the alert doesn't cover anything important.
=> Alert size and position fixed

Games/types/Mafia/Action.js, Games/types/Mafia/Item.js, Games/types/Mafia/items/Gun.js, Games/types/Mafia/items/Suit.js, Games/types/Mafia/roles/cards/SnoopItems.js, react_main/src/pages/Play/Learn/LearnMafia.jsx
- moved snoop action to library
- allow snooping role items like mop for janitor and robe for mason/ cult
- allow snooping specific gun and suit type
- added descriptions to learn tab
Fixes #221 
Fixes #468
=> feat(snoop): add role items and item descriptions

react_main/src/Main.jsx
The schema is changing from boolean to string, so I tried to compensate for that. If the "siteColorScheme" setting is set to true in DB, it will display dark theme still. Likewise, if set to false, it will display light theme. Honestly it looks like it still worked fine regardless, but put in these checks to make sure. Also, defaulting to auto setting for best UX.
=> Make dark/light theme UX better

react_main/src/json/swears.js, react_main/src/lib/profanity.js
- Fixes #737 
- Also added some common swears to `swears.json`
=> fix: profanity filter no longer replaces numbers

Games/core/Game.js
Original Issue: When the guiser target leaves game, they are able to leave successfully from game. However, from lobby, they are prompted with "still in game" situation and when they press to leave game there, it kicks the disguiser out as well.
Solution: Ensure that when leaving a game, the redis cache that holds active games for a user is cleared using the correct user ID and not the userID of the swapped.
Risk Factor: Low - this should only be in affect when swapped is called into question. All other code paths and flows will be unaffected.
=> Disguiser Bug: Use correct userID to delete from redis

react_main/package.json, react_main/src/css/game.css, react_main/src/css/user.css, react_main/src/pages/Game/Game.jsx, react_main/src/pages/User/User.jsx, react_main/src/utils.jsx
Added NPM package for color contrast ratio calculation. Add brightness filter to user-selected color text based on the ratio calculation, darker/brighter depending on the difference.
Will close #724.
=> Adjust Colors based on contrast

Games/core/Game.js, Games/core/VegKickMeeting.js, Games/types/Mafia/roles/cards/ProposeMarriage.js
Fixes #785 
Fixes #774 
**starting the instant meeting resets kicks**
**made bride meeting veggable**
**fixed the kicking 2/2 spam we saw yesterday**
=> feat: instant meetings reset kicks [fixes reset kicks]

data/renamedRoles.js, test/Games/Mafia.test.js
This is kinda important, it causes people who picked the new agent (i.e. the one that contacts by role) to always pick seeker (the one that guesses adversary).
=> important fix(renamed roles): do not rename agent/ spy, fix test case

react_main/src/css/forums.css
Added a fix in css to force forum names to always have `filter: brightness(1)` so the color does not change.
=> Forcing username color to stay constant

Games/core/VegKickMeeting.js
This is to fix the bug where dawnstart games do not have a kick option. It will show "None".
The user reported the bug with the JFK setup
=> fix: force kick meeting to always generate target
