BeyondMafia/BeyondMafia-Integration

docs/dependencies.md
docs/mongo-redis-docker.md
docs/mongo.md

hope it will help others looking to get started
[preview](https://github.com/pikulet/beyondmaf/blob/setup-guide/docs/dependencies.md)

docs: add setup guide for external api and mongo

---

README.md
docs/dependencies.md

[preview](https://github.com/pikulet/beyondmaf/blob/docs/docs/dependencies.md)

docs: add recaptcha and firebase auth to setup guide

---

Games/types/Mafia/Player.js

Fixes #23 
(I still can't get testing running HE HE HE)

Prevents dead players from extending day

---

README.md

- Added chat port to example .env in readme
- Updated repo link in readme

Added chat port to readme

---

react_main/src/pages/Game/Game.jsx

Updated PR of #34 implementing autocompletion for **all** non username characters.
Will also enable easier implementation of posting user avi's in chat with %User, which I'm looking at implementing soon.

Tab autocomplete support for all valid characters

---

docs/bot-games.md
docs/dependencies.md
docs/dev-mode.md
docs/mongo-redis-docker.md

[preview](https://github.com/pikulet/beyondmaf/blob/docs/docs/bot-games.md)

docs: add guide for starting games with bots

---

.vscode/launch.json
Games/core/Game.js
Games/core/Player.js

as mentioned in the other PR, we do not deal with removing effects in the gy first

bugfix: remove effects postgame

---

Games/types/Mafia/roles/cards/Dream.js

just had to add a filter to the list of players

bug fix: dreaming about self

---

react_main/src/css/game.css

[large screen.webm](https://user-images.githubusercontent.com/24848927/212448828-afda850d-bba6-47db-bad3-c2f9937ab20c.webm)
[small screen.webm](https://user-images.githubusercontent.com/24848927/212449046-ba950658-405f-4545-9440-0c69f0ef595b.webm)

ui fix: add 70% height limit on long whisper/contact list

---

react_main/src/css/form.css

ui: add hex color picker

---

react_main/src/pages/Game/Game.jsx

This fixes #95. Doesn't rely on env data so should just work anywhere, tested it locally.

Fix game icon link

---

react_main/src/components/Popover.jsx
react_main/src/components/Roles.jsx
react_main/src/components/Setup.jsx

call popovers for role info in open setups

---

Games/types/Mafia/items/AssoGun.js
Games/types/Mafia/items/Gun.js
Games/types/Mafia/roles/Mafia/Sniper.js
Games/types/Mafia/roles/Village/Deputy.js
Games/types/Mafia/roles/Village/Sheriff.js
Games/types/Mafia/roles/cards/AssoGunGiver.js

Reverts r3ndd/BeyondMafia-Integration#168
https://beyondmafia.com/game/9I2XWfTQA/review
@pikulet A bug was introduced here. I believe it was your use of the OR operator in the reveal setting.

Revert "refactor: gun rework, reduce number of types of guns"

---

Games/types/Mafia/roles/cards/WinByLynching.js
Games/types/Mafia/roles/cards/WinIfLynched.js

fix: allow executioner and jester to joint win

---

Games/core/Meeting.js

- jail meeting has no whisper option
- village meeting still has whisper option during eclipse
fixes #94

bugfix: disable whispers for anon meetings

---

Games/types/Mafia/roles/cards/CleanDeath.js

bugfix: janitor cleans last will

---

react_main/src/pages/Game/Game.jsx

turn on voting log by default

---

Games/types/Mafia/roles/cards/SwapVisitors.js

Fixed bug where game would crash if driver picked no one for Drive target A and someone for target B

fixed driver crash bug

---

react_main/src/components/Basic.jsx
react_main/src/pages/Game/Game.jsx

- Added support for %Username to display a user's avatar while in game.
- My first few lines of react code 😃 (yay!)

[Tested] Added inline avatars with %Username

---

react_main/src/components/Basic.jsx
react_main/src/pages/Game/Game.jsx

Reverts r3ndd/BeyondMafia-Integration#183
This currently breaks links, so I'm reverting for now.

Revert "[Tested] Added inline avatars with %Username"

---

test/Games/Mafia.test.js

jester can now joint with other teams that rely on a majority, e.g. mafia

tests: fix jester test case after adding againOnFinished

---

Games/types/Mafia/roles/cards/WinByLynching.js

Have changed the listener to `rolesAssigned` instead. Fixes #201

bugfix: exe does not get target on daystart

---

data/roles.js

Added that resurrectionist/necromancer action can only be done once per game

Updated Resurrectionist/Necromancer Descriptions

---

react_main/src/css/game.css
react_main/src/pages/Game/Game.jsx

Also changed css to increase gap between players to reduce chance of clicking wrong player, as well as changed cursor to pointer on target hover.

[Tested] Added ability to vote by clicking target

---

react_main/src/pages/Game/Game.jsx

- Click-to-vote as sheriff during day will fire gun instead of voting during town meeting
- Quick PR to disable this bug until I or someone fixes properly

[hotfix] disables vote-on-click

---

Games/types/Mafia/roles/cards/Dream.js

bugfix: dreaming about self

---

Games/core/Meeting.js
Games/types/Mafia/roles/cards/TailorSuit.js

Refactored Tailor with role target meeting and randomized target list so that it doesn't correspond with player order in game.

[bugfix] fixed role target meetings

---

Games/types/Mafia/roles/cards/DieIfMasonsConvertMafia.js
Games/types/Mafia/roles/cards/JailTarget.js

this allows people to gain immunity to these kills on virgin night
Fixes #236

bugfix: add dominates check for mismason and jail kills

---

Games/types/Mafia/Game.js
react_main/src/pages/User/Profile.jsx

fix(stats): vegged games (by other players) no longer change your winrate + display unabandoned game count

---

Games/types/Mafia/roles/cards/Dream.js

Just check if the actor is alive.
Fixes #296

Fixed dead dream.

---

Games/types/Mafia/items/Invitation.js

Banquet message roles are no longer in player order

randomized banquet message

---

README.md
docs/role-icons.md

[preview](https://github.com/pikulet/beyondmaf/blob/adding-role-icons/docs/role-icons.md)

docs: add guide on contributing role icons

---

react_main/src/pages/User/Profile.jsx

fix: forbid editing other people's profile (FE only)

---

db/db.js

chore: address mongodb deprecation warnings

---

Games/core/Meeting.js
lib/Random.js

Wow, that was easy.
TESTED with following leak percentages: 0%, 5%, 85%, 100%. Also tested with a game that had whispers disabled. None of the test cases broke, and they worked as expected.

Whispers leak now!

---

Games/types/Mafia/meetings/Village.js

i hardcoded the value in
I wanted to add it to data/constants but the secondary timer is only used for mafia's village meeting, so maybe this is enough
Resolves #354

refactor: increased secondary timer from 30s to 1minute

---

react_main/src/components/Basic.jsx
react_main/src/css/user.css
react_main/src/pages/Game/Game.jsx

some small example:
There's no issue for this, just something I wanted to do

add inline avatar posting

---

data/roles.js

Fixes commits from PRs #348 and #304

Fixes errors in roles.js data

---

Games/types/Mafia/roles/cards/MessageSender.js
Games/types/Mafia/roles/cards/Visit.js

sorry about it!
roles affected: Jester Messenger Courier Visitor Trespasser

bugfix: fix targets for messengesender and visit

---

Games/types/Mafia/roles/cards/TailorSuit.js

bugfix: check null suit for tailor

---

Games/types/Mafia/roles/Village/Babushka.js
Games/types/Mafia/roles/cards/ConvertImmune.js
Games/types/Mafia/roles/cards/MimicRole.js
Games/types/Mafia/roles/cards/SwapRoles.js
data/roles.js

Fixes #60 
- affected roles: maid mimic mason cult
- maid won't die because it's action is "hidden"

bugfix: add babushka conversion immunity

---

Games/types/Mafia/roles/cards/KillVisitorsWhileDead.js

else mummy will kill the vigi, like bomb

bugfix(mummy): do not trigger abilities the night it is killed

---

README.md
docs/github-codespace.md
docs/setup-dependencies.md
docs/setup-mongo-redis-docker.md

allows remote setup of this repository
[preview](https://github.com/pikulet/beyondmaf/blob/docs-codespace/docs/github-codespace.md)
@R9H9 you can try it out

docs: add github codespace documentation

---

react_main/src/pages/Play/Host/Host.jsx

bugfix: fix setup searching for page > 1

---

Games/types/Resistance/Game.js
Games/types/Resistance/Role.js
Games/types/Resistance/roles/Resistance/Merlin.js
Games/types/Resistance/roles/Resistance/Percival.js
Games/types/Resistance/roles/Spies/Morgana.js
Games/types/Resistance/roles/Spies/Oberon.js
Games/types/Resistance/roles/Spies/Spy.js
Games/types/Resistance/roles/cards/Foresight.js
Games/types/Resistance/roles/cards/KnowMerlin.js
Games/types/Resistance/roles/cards/Oblivious.js
Games/types/Resistance/roles/cards/SpyCore.js
Games/types/Resistance/roles/cards/TeamCore.js
data/roles.js
react_main/src/pages/Game/ResistanceGame.jsx

[Resistance] added avalon roles

---

Games/core/Game.js
Games/types/Mafia/Game.js
Games/types/Mafia/meetings/Village.js

Also fixes driver/cyclist veg bug.
Also removed condition to kick player when vegging.
Fixes #232 and #56

Fix witch veg bug

---

db/schemas.js
react_main/src/css/user.css
react_main/src/pages/User/Profile.jsx
react_main/src/pages/User/Settings.jsx
react_main/src/pages/User/User.jsx
routes/user.js

Continuation of PR #422 
I made a separate PR and branch because I didn't want to merge the react build changes every time there's a new front end change to master, thus, requiring a new set of reviews every single time.

Profile video

---

Games/types/Mafia/roles/cards/DayShooter.js

bugfix: tinkerer does not give gun from voteoff

---

Games/types/Mafia/effects/Poison.js
Games/types/Mafia/roles/cards/RedirectAction.js
Games/types/Mafia/roles/cards/SwapVisitors.js
docs/info-mafia-constants.md

bugfix: add uncontrollable label for delayed actions

---

react_main/src/pages/Game/Game.jsx

refers to the sound played in the last 5 seconds of a phase
personally 5s isn't gonna do much especially when i have to vote... 
let me know if 15s is too annoying xD

refactor: increase tick from 5s to 15s

---

react_main/src/components/Roles.jsx

Fixes #416 
my mistake from the tree PR #174

bugfix: do not show disabled roles on search

---

data/roles.js

here are some rewritten clearer wording for roles, let me know if any changes need to be made!

Fix role description

---

react_main/src/pages/Game/Game.jsx

Reverses #301 
Tested, did not find any issues. I asked around the bug was only reported by one user so it could be a mistaken bug report.
[Screencast from 06-03-2023 02:12:40.webm](https://user-images.githubusercontent.com/24848927/223431842-888be3a9-ebad-4751-a4c5-ac6121d1e579.webm)

feat(vote): re-enable click to vote

---

Games/types/Mafia/items/Armor.js

bugfix: do not shatter armour if healed

---

react_main/src/pages/Game/Game.jsx

bugfix(textinput): replace newlines with space

---

react_main/src/pages/Play/Host/Host.jsx
routes/setup.js

feat: add tab for ranked setups

---

Games/types/Mafia/roles/cards/AskDeadQuestion.js

fix: mourner percents rounded

---

Games/types/Mafia/roles/Mafia/Apprentice.js
data/roles.js

I've added Apprentice.
This was split off from #507.

Added Apprentice

---

Games/core/Player.js
Games/types/Mafia/Player.js
Games/types/Mafia/roles/cards/Bloodthirsty.js

Blood is now global (can be used by other roles, etc. in the future)
This also adds, player.data, which could be used in the future to add more global variables.
egg recommended having a check for blood, I am currently working on that, but this works for now.

Global Blood, player.data Added

---

Games/types/Mafia/roles/cards/Scatterbrained.js

I fixed Scatterbrained so that it doesn't incorrectly replace the name of the Mafia kill.

Fixed Scatterbrained

---

Games/types/Mafia/roles/cards/Bloodthirsty.js

Forgot to change a this.data.blood to this.player.data.blood #613

Bloodthirsty Typo Fix

---

react_main/src/pages/Game/Game.jsx

- Adds ability to autocomplete "@everyone" if Tab fails to match any other user
- Saves me typing time in-game :)
Some test cases shown below:

feat: Add Tab autocompletion for "@everyone"

---

Games/types/Mafia/roles/Independent/Autocrat.js
Games/types/Mafia/roles/cards/WinInsteadOfVillage.js
data/roles.js

I've added Autocrat.
This was split off from #507.

Added Autocrat

---

Games/types/Mafia/roles/cards/MessageSender.js

I've fixed the bug regarding the message not being cleared.

Messenger/Courier Message Fix

---

Games/types/Mafia/Action.js

Tested by creating 5 forager 1 thulu setups and ran through all those items

fix: add icons for queueitem alert

---

react_main/src/css/game.css
react_main/src/pages/Game/Game.jsx

feat(chat, greentext): Implements greentext using >

---

react_main/src/Main.jsx
react_main/src/components/Emotes.jsx
react_main/src/pages/Chat/EmoteList.jsx

- alphanum sorted emotes and improved emotify logic (reduced time complexity)
- Created an emotes list available at https://beyondmafia.com/emotes or (wherever you are testing)
- Dynamic list so should always be up to date, implements #664 
ps. would be great if someone could check that the site chat still works 🥳, wasn't able to test on my end

Docs: Added emotes list

---

react_main/src/pages/Game/Game.jsx

fix: quoting breaks the frontend greentext check

---

react_main/src/pages/Game/Game.jsx

fix: able to click-to-vote people even if they can't vote

---

Games/types/Mafia/effects/Insanity.js

"There is no great genius without some touch of madness."
~ Aristotle
Alas, I have no doubt that it will work as intended this time. With both these thoughts in the forefront of mind, I have finally implemented AES encryption on Cthulhu afflicted individuals, updating the makeStringInsane function to be more culturally appropriate in today's society.
Implements #5

upgraded insanity speech filter

---

Games/types/Mafia/roles/cards/Scatterbrained.js

fix: scatterbrained modifier does not reveal

---

Games/types/Mafia/roles/cards/TrickedWares.js

Fixes #619 
The code is from sleepwalker.

fix: trickster is now a visiting role

---

react_main/src/lib/profanity.js

fix: do not replace with leet mappings if no profanities were detected

---

Games/types/Mafia/effects/VoteBlind.js
Games/types/Mafia/roles/Village/Leader.js
Games/types/Mafia/roles/cards/LeaderlessOnDeath.js
Games/types/Mafia/templates/stateEvents.js
data/roles.js

This is probably the simplest of the needed roles
Not sure if there's anything I haven't missed though that I need to create a reference to in order for the code to work; this role should parallel lightkeeper in various aspects, hence most of the code is adapted from that role

Add Leader Role

---

react_main/src/css/alerts.css
react_main/src/css/main.css

I don't see any issues so I guess this is okay.
First attempt of coding on Windows using GitHub Desktop so I can maybe blame anything wrong on that.

refactor(ui): Fixed the alert on mobile not being centered

---

data/roles.js

modified role description for cyclist and driver to remove clause for visiting as in issue#723.

modified wrong role description for cyclist/driver

---

Games/types/Mafia/roles/cards/WinInsteadOfVillage.js

I fixed Autocrat.
Thanks @ChaoticNeutralGnome for catching the error!

Fix Autocrat

---

Games/types/Mafia/templates/death.js

rewrote famine death message to remove reference to the great famine

rewrote famine message

---

react_main/src/css/emotes.css
react_main/src/pages/Chat/EmoteList.jsx

Made the emote page look nicer

Made the emote page look nicer

---

Games/types/Mafia/roles/cards/SleepWalk.js

Fixes #558 
that priority is just to ensure it visits the night it is killed

fix: sleepwalker only visits while alive

---

Games/core/Game.js
Games/types/Mafia/roles/Independent/Mistletoe.js
Games/types/Mafia/roles/Mafia/Inquisitor.js
Games/types/Mafia/roles/Mafia/Poisoner.js
Games/types/Mafia/roles/Mafia/Spy.js
Games/types/Mafia/roles/Village/Agent.js
Games/types/Mafia/roles/Village/Celebrity.js
Games/types/Mafia/roles/Village/Drunk.js
Games/types/Mafia/roles/Village/Gunsmith.js
Games/types/Mafia/roles/Village/Seeker.js
data/renamedRoles.js
data/roles.js
react_main/src/css/roles.css

I've started reflavouring the roles.
For ease of testing and things, I'll leave the reflavouring of the Monster roles for another PR.

Reflavouring Roles

---

Games/types/Mafia/roles/Monsters/Mindwarper.js
Games/types/Mafia/roles/cards/MindShifter.js
data/roles.js

A role that is similar to cthulu, but can drive people insane more consistently and allows for more counterplay.

Added Mindwarper

---

Games/types/Mafia/roles/cards/Carol.js
test/Games/Mafia.test.js

fix: caroler is able to carol janitor

---

Games/core/Game.js
Games/core/Player.js
Games/types/Mafia/roles/cards/AnonymizeMafia.js
Games/types/Mafia/roles/cards/BecomeDeadRole.js
Games/types/Mafia/roles/cards/Bloodthirsty.js
Games/types/Mafia/roles/cards/BreadGiver.js
Games/types/Mafia/roles/cards/ElectionResults.js
Games/types/Mafia/roles/cards/GiveTurkeyOnDeath.js
Games/types/Mafia/roles/cards/JailTarget.js
Games/types/Mafia/roles/cards/MimicRole.js
Games/types/Mafia/roles/cards/PotionCaster.js
Games/types/Mafia/roles/cards/PublicReveal.js
Games/types/Mafia/roles/cards/SeanceTarget.js
Games/types/Mafia/roles/cards/SwapRoles.js
Games/types/Mafia/roles/cards/WinByLynching.js
docs/info-core-game-mechanics.md

Refactored rolesassigned into roleassigned with a player param, which is automatically called for all players at the start and anytime a role is set using setRole (unless the noEmit param is true)

refactored rolesassigned

---

react_main/src/components/Roles.jsx
react_main/src/css/game.css
react_main/src/pages/Game/Game.jsx

[Screencast from 29-04-2023 01:01:08.webm](https://user-images.githubusercontent.com/24848927/235209134-6bc40f15-3392-4ca2-8020-7de059fd4e64.webm)
Fixes #718

add rolemarker at the side

---

routes/comment.js

bugfix: check permission when deleting comments on own profile

---

Games/core/Meeting.js

fixes #427 
i checked using lawyer and mustact

fix(core): mustact actions show empty option when no options are available

---

Games/types/Mafia/Action.js
Games/types/Mafia/roles/cards/ArmorGiver.js
Games/types/Mafia/roles/cards/AssoGunGiver.js
Games/types/Mafia/roles/cards/BreadGiver.js
Games/types/Mafia/roles/cards/CatGiver.js
Games/types/Mafia/roles/cards/GiveCrystal.js
Games/types/Mafia/roles/cards/GiveKnife.js
Games/types/Mafia/roles/cards/GiveSnowball.js

makes icon changes clearer
im making some other changes in separate PRs for easier testing

refactor(mafia): clean up item alerts

---

Games/types/Mafia/roles/cards/GivePresents.js

Fixes #799 
currently santa messages have the "gift" icon instead of gun/ armour etc

fix: santa message is consistent with other roles

---

Games/types/Mafia/roles/cards/GiveVisitorsGuns.js

refactor(funsmith): checks aliveness, checks multi actor

---

data/constants.js

maxPlayers changed from 50 to 20.
As long as we have a small playerbase these games are detrimental.

Lower max player number from 50 to 25

---

react_main/src/pages/User/Profile.jsx

bugfix: delete friend only shows on your own profile

---

react_main/src/Main.jsx

Replace Link to Wiki with Emotes Page
